apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2025-02-02T12:42:52Z"
  generation: 17
  name: jenkins
  namespace: argocd
  resourceVersion: "3640214"
  uid: e05b6e46-dfb3-4315-ba58-25b67f93d91b
spec:
  destination:
    namespace: ci-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins
    repoURL: https://alex-agd.github.io/helm-jenkins/
    targetRevision: 0.4.0
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2025-02-02T12:42:52Z"
    deployedAt: "2025-02-02T12:42:53Z"
    id: 0
    initiatedBy:
      automated: true
    revision: 0.4.0
    source:
      chart: jenkins
      repoURL: https://alex-agd.github.io/helm-jenkins/
      targetRevision: 0.4.0
  operationState:
    finishedAt: "2025-02-02T12:42:53Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: 0.4.0
        syncOptions:
        - CreateNamespace=true
    phase: Succeeded
    startedAt: "2025-02-02T12:42:52Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: 'namespace/ci-cd configured. Warning: resource namespaces/ci-cd is
          missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically.'
        name: ci-cd
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ServiceAccount
        message: 'serviceaccount/jenkins configured. Warning: resource serviceaccounts/jenkins
          is missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically.'
        name: jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Secret
        message: 'secret/jenkins-secret configured. Warning: resource secrets/jenkins-secret
          is missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically.'
        name: jenkins-secret
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: 'configmap/jenkins-config configured. Warning: resource configmaps/jenkins-config
          is missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically.'
        name: jenkins-config
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: 'configmap/basic-security configured. Warning: resource configmaps/basic-security
          is missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically.'
        name: basic-security
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: 'clusterrolebinding.rbac.authorization.k8s.io/jenkins reconciled.
          reconciliation required update. clusterrolebinding.rbac.authorization.k8s.io/jenkins
          configured. Warning: resource clusterrolebindings/jenkins is missing the
          kubectl.kubernetes.io/last-applied-configuration annotation which is required
          by  apply.  apply should only be used on resources created declaratively
          by either  create --save-config or  apply. The missing annotation will be
          patched automatically.'
        name: jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: 'service/jenkins configured. Warning: resource services/jenkins is
          missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically.'
        name: jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: 'deployment.apps/jenkins configured. Warning: resource deployments/jenkins
          is missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically.'
        name: jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: autoscaling
        hookPhase: Running
        kind: HorizontalPodAutoscaler
        message: 'horizontalpodautoscaler.autoscaling/jenkins configured. Warning:
          resource horizontalpodautoscalers/jenkins is missing the kubectl.kubernetes.io/last-applied-configuration
          annotation which is required by  apply.  apply should only be used on resources
          created declaratively by either  create --save-config or  apply. The missing
          annotation will be patched automatically.'
        name: jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v2
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: 'ingress.networking.k8s.io/ingress-jenkins configured. Warning: resource
          ingresses/ingress-jenkins is missing the kubectl.kubernetes.io/last-applied-configuration
          annotation which is required by  apply.  apply should only be used on resources
          created declaratively by either  create --save-config or  apply. The missing
          annotation will be patched automatically.'
        name: ingress-jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 0.4.0
      source:
        chart: jenkins
        repoURL: https://alex-agd.github.io/helm-jenkins/
        targetRevision: 0.4.0
  reconciledAt: "2025-02-02T12:50:41Z"
  resources:
  - kind: ConfigMap
    name: basic-security
    namespace: ci-cd
    status: Synced
    version: v1
  - kind: ConfigMap
    name: jenkins-config
    namespace: ci-cd
    status: Synced
    version: v1
  - kind: Namespace
    name: ci-cd
    status: Synced
    version: v1
  - kind: Secret
    name: jenkins-secret
    namespace: ci-cd
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: jenkins
    namespace: ci-cd
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: jenkins
    namespace: ci-cd
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: jenkins
    namespace: ci-cd
    status: Synced
    version: v1
  - group: autoscaling
    health:
      message: the HPA controller was able to get the target's current scale
      status: Healthy
    kind: HorizontalPodAutoscaler
    name: jenkins
    namespace: ci-cd
    status: Synced
    version: v2
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: ingress-jenkins
    namespace: ci-cd
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: jenkins
    status: Synced
    version: v1
  sourceType: Helm
  summary:
    externalURLs:
    - http://jenkins.k8s-5.sa/
    images:
    - jfrog.it-academy.by/public/jenkins-ci:aleksey_do
  sync:
    comparedTo:
      destination:
        namespace: ci-cd
        server: https://kubernetes.default.svc
      source:
        chart: jenkins
        repoURL: https://alex-agd.github.io/helm-jenkins/
        targetRevision: 0.4.0
    revision: 0.4.0
    status: Synced
