apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  destination:
    namespace: ci-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins
    repoURL: https://alex-agd.github.io/helm-jenkins/
    targetRevision: 0.4.0
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

