apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alex-agd/tasker-infra.git
    targetRevision: HEAD
    path: helm/tasker
  destination:
    server: https://kubernetes.default.svc
    namespace: tasker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
