apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://alex-agd.github.io/tasker-infra
    targetRevision: HEAD
    path: helm/tasker
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: postgresql.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: tasker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
