apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Alex-AGD/zabbix-app'
    targetRevision: main
    path: ./
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
